Chapter auth n auth z
hpi-schul-cloud/idm_doc pull request #14
Opened 2021-10-11 13:10 UTC by m1n9el00

# Description

## Links to Tickets or other pull requests

- https://ticketsystem.schul-cloud.org/browse/BC-192

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-10-11 14:09 UTC, mamutmk5 requested changes

2021-10-11 14:09 UTC, mamutmk5 commented on auth.tex
> +Um die Tokengenerierung zu vereinheitlichen, wird für Benutzerkonten mit der Rolle ''sync-system'' statt des Institutionsnamens die Bezeichnung der IDM-Domäne verwendet.\\
Müssen wir mal schauen.

2021-10-11 14:09 UTC, mamutmk5 commented on auth.tex
> +\begin{lstlisting}[caption={},frame=tlrb]
Auch hier wieder das Listing sollte einen Beschreibung und ein Label bekommen, da es wandern kann.

2021-10-11 14:09 UTC, mamutmk5 commented on auth.tex
> +Beispiel:
Nicht gut wenn das Listing danach wandert.

2021-10-11 14:35 UTC, m1n9el00 commented on auth.tex
> +Der Ablauf der Autorisierung per OAuth2-Protokoll im Authorization-Code-Flow ist in der folgenden Grafik dargestellt.
> Hier sollte der Englische name verwendet werden. Eine Referenz zur RFC muss sein, referenzen zu so was erfolgen in der regel mit Bibtex ( Erstellt dann auch das Literaturverzeichnis richtig).



> Bei Latex kannst du dir nicht sicher sein das immer das Bild an der Stelle eingebettet wirst wo du es haben willst. Deshalb immer eine Referenzn dazu nemen.

Erledigt, label eingefügt.

2021-10-13 09:05 UTC, mamutmk5 commented on auth.tex
> +Die \textit{Internet Engineering Task Force (IETF)} empfiehlt als Best-Practice-Ansatz die Verwendung des \textit{Authorization Code Grant} \cite[Unterabschnitt~2.1.1]{ietf-oauth-security-topics-18}.
Lass mal "als Best-Practice-Ansatz" weg das liest sich nicht gut.

2021-10-13 09:06 UTC, mamutmk5 commented on auth.tex
> +Über den Access Token erhält der Benutzer schließlich Zugriff auf die REST-API.
Ist das ein wirklich ein neuer Absatz oder nur das ende von den davor?

2021-10-13 09:06 UTC, mamutmk5 commented on auth.tex
> +Der Autorisierungserver sendet einen \textit{Authorization Code} an den \textit{Client}, der diesen wiederum direkt beim Autorisierungsserver gegen den \textit{Access Token} tauscht. \\
Ist der Satz aus zeile 33 nicht die Einleitung der Sätze aus Zeile 42 und 43?

2021-10-13 09:15 UTC, mamutmk5 commented on auth.tex
> +\subsection{OAuth2}
das ist nur eine Section und keine subsection
\chapter ist die erste ziffer \section die zweite und \subsection die Dritte Ziffer
```suggestion
\section{OAuth2}
```

2021-10-13 09:15 UTC, mamutmk5 commented on auth.tex
> +\subsection{OpenID Connect}
auch hier wieder zu einer section machen.
```suggestion
\section{OpenID Connect}
```

2021-10-13 09:16 UTC, mamutmk5 commented on auth.tex
> +\subsection{Einschränkung der Daten}
wieder die Einordung in der Dokumenten Struktur.
```suggestion
\section{Einschränkung der Daten}
```

2021-10-13 10:39 UTC, mamutmk5 approved these changes

2021-10-13 10:52 UTC, merged